# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_coupon_couponrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '33. 用户表'},
        ),
    ]
