# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, verbose_name='贝里'),
        ),
    ]
